name: Build and Publish NuGet

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore packages
      run: nuget restore TWComponents.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build project
      run: msbuild TWComponents.csproj /p:Configuration=Release

    - name: Pack project using .nuspec
      run: nuget pack TWComponents.nuspec -OutputDirectory ./nupkg

    - name: Add GitHub Packages source
      run: nuget sources Add -Name "github" -Source "https://nuget.pkg.github.com/zonex5/index.json" -Username zonex5 -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText
    
    - name: Push to GitHub Packages
      run: nuget push ./nupkg/*.nupkg -Source "github" -ApiKey ${{ secrets.GITHUB_TOKEN }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}